### ISSUE TITLE
Проблемы с преобразованием некоторых треков из txt в gpx

### ISSUE THREAD

**Issue by volniol** [DJm00n/starlineonline2gpx#1]
Некоторые треки по какой-то причине не преобразовываются в формат gpx, выдавая следующую ошибку:

Необработанное исключение: System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   в System.Json.JsonObject.get_Item(String key)
   в starlineonline2gpx.Program.ParseTrack(GPXLib gpx, JsonValue elem, Int32 trackNum) в c:\users\djm00n\documents\visual studio 2015\Projects\starlineonline2gpx\Program.cs:строка 160
   в starlineonline2gpx.Program.Main(String[] args) в c:\users\djm00n\documents\visual studio 2015\Projects\starlineonline2gpx\Program.cs:строка 60

Во вложении проблемный трек. Буду признателен за помощь в решении данной проблемы.

[2019-07-11.txt](https://github.com/DJm00n/starlineonline2gpx/files/3417846/2019-07-11.txt)

**Comment by volniol** [comment]
При преобразовании другого трека возникает немного другая ошибка:

Необработанное исключение: System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   в System.Json.JsonObject.get_Item(String key)
   в starlineonline2gpx.Program.ParseWaypoint(GPXLib gpx, JsonValue elem, Int32 waypointNum) в c:\users\djm00n\documents\visual studio 2015\Projects\starlineonline2gpx\Program.cs:строка 128
   в starlineonline2gpx.Program.Main(String[] args) в c:\users\djm00n\documents\visual studio 2015\Projects\starlineonline2gpx\Program.cs:строка 66

Во вложении трек, вызывающий эту ошибку.

[2019-07-15.txt](https://github.com/DJm00n/starlineonline2gpx/files/3417896/2019-07-15.txt)

**Comment by stepansib** [comment]
The same issue:

```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   at System.Json.JsonObject.get_Item(String key)
   at starlineonline2gpx.Program.ParseTrack(GPXLib gpx, JsonValue elem, Int32 trackNum) in c:\users\djm00n\documents\visual studio 2015\Projects\starlineonline2gpx\Program.cs:line 160
   at starlineonline2gpx.Program.Main(String[] args) in c:\users\djm00n\documents\visual studio 2015\Projects\starlineonline2gpx\Program.cs:line 60
```
[route.txt](https://github.com/DJm00n/starlineonline2gpx/files/7077930/route.txt)

**Comment by Volodymyr2706** [comment]
I also encountered a problem parsing some tracks. After examining the code, I found that the parameter with the key ‘sat_qty’ was missing for some waypoints. This parameter indicates the number of satellites in communication at the time a specific coordinate was recorded. This can be fixed in the code by replacing two lines:
**Sat = Convert.ToString((int)elem["sat_qty"]) ,**
    replace with
**Sat = elem.ContainsKey("sat_qty") ? Convert.ToString((int)elem["sat_qty"]) : "0",**
,and
**Sat = Convert.ToString((int)node["sat_qty"]) ,**
    replace with
**Sat = node.ContainsKey("sat_qty") ? Convert.ToString((int)node["sat_qty"]) : "0",**

We've rebuilt the project and everything works. Tested in June 2026. Thanks to the developer for the idea and all the hard work.
